CREATE DATABASE product_management_system CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE product_management_system;

-- Item Master Table
CREATE TABLE ITEM_MAST (
    Item_Code VARCHAR(10) PRIMARY KEY,
    item_desc VARCHAR(255) NOT NULL,
    Group_Name VARCHAR(50),
    Unit VARCHAR(10),
    Current_Stock INT DEFAULT 0,
    Category VARCHAR(50),
    Reorder_Level INT DEFAULT 0,
    Batch_Size INT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Vendor Master Table
CREATE TABLE VEN_MAST (
    Ven_Code VARCHAR(10) PRIMARY KEY,
    Ven_Name VARCHAR(100) NOT NULL,
    vendor_Location VARCHAR(100),
    Address1 VARCHAR(255),
    Address2 VARCHAR(255),
    City VARCHAR(50),
    Post_Code VARCHAR(10),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Customer Master Table
CREATE TABLE CUST_MAST (
    Cust_Code VARCHAR(10) PRIMARY KEY,
    Cust_Name VARCHAR(100) NOT NULL,
    Address1 VARCHAR(255),
    Address2 VARCHAR(255),
    City VARCHAR(50),
    Post_Code VARCHAR(10),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Purchase Orders Header Table
CREATE TABLE PUR_ORDERS_HEAD (
    Pur_Ord_No VARCHAR(15) PRIMARY KEY,
    Order_Qty INT NOT NULL,
    Order_Date DATE NOT NULL,
    Item_Code VARCHAR(10),
    Ven_Code VARCHAR(10),
    purchaseStatus VARCHAR(20) DEFAULT 'Pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (Item_Code) REFERENCES ITEM_MAST(Item_Code),
    FOREIGN KEY (Ven_Code) REFERENCES VEN_MAST(Ven_Code)
);

-- Purchase Orders Transaction Table
CREATE TABLE PUR_ORDERS_TRAN (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Ord_Rate DECIMAL(10,2),
    Ord_Value DECIMAL(12,2),
    Order_Qty INT NOT NULL,
    Recd_Qty INT DEFAULT 0,
    Pur_Ord_No VARCHAR(15),
    Item_Code VARCHAR(10),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (Pur_Ord_No) REFERENCES PUR_ORDERS_HEAD(Pur_Ord_No),
    FOREIGN KEY (Item_Code) REFERENCES ITEM_MAST(Item_Code)
);

-- Sales Orders Header Table
CREATE TABLE SAL_ORDERS_HEAD (
    Sal_Ord_No VARCHAR(15) PRIMARY KEY,
    Order_Qty INT NOT NULL,
    Order_Date DATE NOT NULL,
    Item_Code VARCHAR(10),
    Cust_Code VARCHAR(10),
    saleStatus VARCHAR(20) DEFAULT 'Pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (Item_Code) REFERENCES ITEM_MAST(Item_Code),
    FOREIGN KEY (Cust_Code) REFERENCES CUST_MAST(Cust_Code)
);

-- Sales Orders Transaction Table
CREATE TABLE SAL_ORDERS_TRAN (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Order_Rate DECIMAL(10,2),
    Order_Value DECIMAL(12,2),
    Order_Qty INT NOT NULL,
    Despatch_Qty INT DEFAULT 0,
    Sal_Ord_No VARCHAR(15),
    Item_Code VARCHAR(10),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (Sal_Ord_No) REFERENCES SAL_ORDERS_HEAD(Sal_Ord_No),
    FOREIGN KEY (Item_Code) REFERENCES ITEM_MAST(Item_Code)
);

-- Transaction Details Table
CREATE TABLE TRANS_DETL (
    Txn_Code VARCHAR(15) PRIMARY KEY,
    Txn_Date DATE NOT NULL,
    Txn_Type VARCHAR(20) NOT NULL,
    Qty_Issued INT DEFAULT 0,
    Qty_Recd INT DEFAULT 0,
    Item_Code VARCHAR(10),
    Ven_Code VARCHAR(10),
    Cust_Code VARCHAR(10),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (Item_Code) REFERENCES ITEM_MAST(Item_Code),
    FOREIGN KEY (Ven_Code) REFERENCES VEN_MAST(Ven_Code),
    FOREIGN KEY (Cust_Code) REFERENCES CUST_MAST(Cust_Code)
);

-- Production Budget Table
CREATE TABLE PROD_BUDGET (
    id INT AUTO_INCREMENT PRIMARY KEY,
    CurMonth VARCHAR(7) NOT NULL,
    Month_Bud_Qty INT NOT NULL,
    Item_Code VARCHAR(10),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (Item_Code) REFERENCES ITEM_MAST(Item_Code)
);

-- Vendor Item Table
CREATE TABLE VENDOR_ITEM (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Item_Code VARCHAR(10),
    Ven_Code VARCHAR(10),
    Final_Rate DECIMAL(10,2),
    Upd_Date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (Item_Code) REFERENCES ITEM_MAST(Item_Code),
    FOREIGN KEY (Ven_Code) REFERENCES VEN_MAST(Ven_Code),
    UNIQUE KEY unique_vendor_item (Item_Code, Ven_Code)
);